Removed BibleUploader, related codes and language references from gb.lang and us.lang
quelea-projection/Quelea pull request #407
Opened 2021-10-02 16:48 UTC by raernon

I think it's done, but please check.

2021-10-02 17:01 UTC, berry120 requested changes
Hey, thanks for the PR!

Few changes here - and can we also remove the `bible.load.error.title` and `bible.load.error.question` from all the other language files too? (I know it's a chore, but it shouldn't take too long using ctrl+f to find the relevant lines in each file.)

2021-10-03 07:30 UTC, raernon commented
All fixed, please check.

2021-10-03 08:02 UTC, berry120 approved these changes

2021-10-03 08:02 UTC, berry120 commented
Thanks!

2021-10-03 08:02 UTC, merged